### ISSUE TITLE
config vapid keys does not seem to work

### ISSUE THREAD

**Issue by superchris** [midarrlabs/web-push-elixir#11]
The README suggests you can add vapid keys to config like so:

```elxir
config :web_push_elixir,
  vapid_public_key: "key",
  vapid_private_key: "key",
  vapid_subject: "mailto:admin@email.com"
```

but this fails at runtime. In the code, it appears to reference env variables direction instead at `web_push_elixir.ex:111`

**Comment by trueChazza** [comment]
`0.4.0`

Hi, yes sorry I hadn't tagged the new version that included the readme changes. 

I've done that now, please try again and let me know if you run into any issues 😄

**Comment by superchris** [comment]
thanks worked great! you are fast :)
